Output lint-helper-demo.gif

Set Theme "Dracula"
Set Framerate 120
Set PlaybackSpeed 1.2
Set TypingSpeed 60ms
Set WindowBar ColorfulRight
Set Width 1280
Set Height 720

Hide Type cd .. Enter Ctrl+L Show
Type "./lint-helper.sh -jc lint" Sleep 1.5s Enter Sleep 6s
Type "./lint-helper.sh -c format" Sleep 1.5s Enter Sleep 4s
Type "./lint-helper.sh -ja all" Sleep 1.5s Enter Sleep 10s
Type "./lint-helper.sh -j -c lint -c format" Sleep 1.5s Enter Sleep 10s
