name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache
      uses: actions/cache@v3
      with:
        # TODO: FIX ME
        path: |
          ~/.ccache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}
