name: Report Doc
run-name: Generating Report Doc for ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    branches:
    - main

concurrency:
  group: "report"
  cancel-in-progress: true

jobs:
  Generate-Report:
    runs-on: ubuntu-20.04
    defaults:
      run:
        # Will change in main repo
        working-directory: .
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: latexmk texlive-science texlive-bibtex-extra texlive-latex-extra
          method: timestamp
      - name: Build Report Doc
        run: make
      - name: Archive Report Doc Build
        uses: actions/upload-artifact@v3
        with:
          name: Artifact-Report-Doc-Pdf-Build
          path: ./build/report.pdf
