name: Lint
run-name: Linting ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:
      - main

env:
  CLANG_TIDY_VERSION: "16.0.4"
  VERBOSE: 1

jobs:
  Clang-Tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # slighty repetitive... ?
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Check Lint
        run: |
          ./lint-helper.sh -c lint

      - name: Check Format
        run: |
          ./lint-helper.sh -c format

      - name: Test-Build Documentation
        uses: mattnotmitt/doxygen-action@v1.9.5
