name: Lint
run-name: Linting ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:

env:
  # Might be too new tho lol
  CLANG_TIDY_VERSION: "16.0.4"
  VERBOSE: 1

jobs:
  Clang-Tidy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # TODO: CACHE?!
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Check Lint
        run: |
          ./lint-helper.sh -c lint

      - name: Check Format
        run: |
          ./lint-helper.sh -c format
