name: CI Testing
run-name: Running CI Tests on ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:

env:
  CLANG_TIDY_VERSION: "16.0.4"
  VERBOSE: 1

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        compiler:
          - llvm-16.0.4
          - gcc-11

    steps:
      - name: Check for llvm version mismatches
        if: ${{ contains(matrix.compiler, 'llvm') && !contains(matrix.compiler, env.CLANG_TIDY_VERSION) }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('There is a mismatch between configured llvm compiler and clang-tidy version chosen')

      - uses: actions/checkout@v3

        # TODO: FIX ME
      - name: Setup Cache
        uses: ./.github/actions/setup_cache
        with:
          compiler: ${{ matrix.compiler }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          ccache: true # but are we even using it tho, lmao
          clangtidy: ${{ env.CLANG_TIDY_VERSION }}

      - name: Testiiiing!
        run: |
          make run-tests

      - name: Archive gcc Build Output
        # Once for each OS, and only if on main branch?
        if: ${{ startsWith(matrix.compiler, 'gcc') && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts-${{ runner.OS }}-build-outputs-${{ matrix.compiler }}
          path: build/*
